name: tw_weather_pipeline

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: tw_test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  application:
    build:
      context: .
    container_name: pipeline
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://myuser:mypassword@postgres:5432/tw_test"
    volumes:
      - ./:/app
    command: ["python", "-m", "main"]

volumes:
  postgres_data:
