[tool.black]
line-length = 120
target-version = ['py311']
skip-string-normalization = true
exclude = '''
/(
      \.eggs         # exclude a few common directories in the
    | \.idea
    | \.git          # root of the project
    | \.venv
    | build
    | temp
)/
'''

